name: Build Windows EXE and Release

on:
  push:
    tags:
      - 'v*'  # 当你推送 v1.0.0 这样的标签时触发

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Build EXE with PyInstaller
        run: |
          pyi-makespec --onefile --icon=assets/run.ico ${{ github.event.repository.name }}.py
          pyinstaller ${{ github.event.repository.name }}.spec
          pyi-makespec --onefile --icon=assets/run.ico --console  ${{ github.event.repository.name }}_debug.py
          pyinstaller ${{ github.event.repository.name }}_debug.py

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.exe
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          generate_release_notes: true 
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}